/**
 * Extract text from every PDF in support/data/resources.json.
 *
 * Outputs:
 *   support/data/extracted/<slug>.md   — one per successfully extracted PDF
 *   support/data/extracted/INDEX.md    — listing of every doc with status
 *
 * Designed to run in GitHub Actions on ubuntu-latest with poppler-utils
 * (pdftotext) installed. Local runs work too as long as pdftotext is on PATH.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const exec = promisify(execFile);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const RESOURCES = path.join(ROOT, 'support/data/resources.json');
const OUT_DIR = path.join(ROOT, 'support/data/extracted');
const TMP_DIR = path.join(os.tmpdir(), 'lynx-pdf-extract');

const CONCURRENCY = 6;
const FETCH_TIMEOUT_MS = 30_000;

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 80);
}

function isPdfUrl(url) {
  if (!url) return false;
  try {
    const u = new URL(url);
    return u.pathname.toLowerCase().endsWith('.pdf');
  } catch {
    return false;
  }
}

async function fetchWithTimeout(url, ms) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), ms);
  try {
    const res = await fetch(url, {
      signal: ctrl.signal,
      headers: { 'User-Agent': 'LynxPro-DocExtractor/1.0 (+github.com/dixonrand/LynxPro)' },
    });
    return res;
  } finally {
    clearTimeout(timer);
  }
}

async function extractOne(doc, slug) {
  const pdfPath = path.join(TMP_DIR, `${slug}.pdf`);
  const res = await fetchWithTimeout(doc.url, FETCH_TIMEOUT_MS);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 200) throw new Error(`too small (${buf.length} bytes)`);
  await fs.writeFile(pdfPath, buf);

  let stdout = '';
  try {
    const result = await exec('pdftotext', ['-layout', '-enc', 'UTF-8', pdfPath, '-'], {
      maxBuffer: 64 * 1024 * 1024,
    });
    stdout = result.stdout;
  } finally {
    await fs.unlink(pdfPath).catch(() => {});
  }

  const text = stdout.replace(/\r\n/g, '\n').replace(/[ \t]+\n/g, '\n').trim();
  if (text.length < 40) throw new Error(`empty extraction (${text.length} chars)`);
  return { text, bytes: buf.length };
}

function renderDocMd(doc, slug, text) {
  const meta = [
    `**Title:** ${doc.title}`,
    `**Slug:** \`${slug}\``,
    `**Category:** ${doc.category}${doc.subcategory ? ' › ' + doc.subcategory : ''}`,
    `**Type:** ${doc.type}`,
    `**Source URL:** ${doc.url}`,
  ];
  if (doc.use) meta.push(`**Use:** ${doc.use}`);
  return `# ${doc.title}\n\n${meta.join('\n')}\n\n---\n\n${text}\n`;
}

function renderIndexMd(rows, sourceCount) {
  const ok = rows.filter((r) => r.status === 'extracted');
  const failed = rows.filter((r) => r.status === 'failed');
  const totalChars = ok.reduce((s, r) => s + r.chars, 0);

  const lines = [];
  lines.push('# Extracted Documents Index');
  lines.push('');
  lines.push('Auto-generated by `support/scripts/extract-docs.js`. Do not edit by hand.');
  lines.push('');
  lines.push(
    `**${ok.length}** of **${sourceCount}** PDFs successfully extracted ` +
      `(${totalChars.toLocaleString()} characters total).`
  );
  lines.push('');
  lines.push('Each extracted doc lives at `support/data/extracted/<slug>.md`.');
  lines.push('');
  lines.push('## Available documents');
  lines.push('');

  // Group by category
  const byCat = new Map();
  ok
    .sort((a, b) => a.title.localeCompare(b.title))
    .forEach((r) => {
      if (!byCat.has(r.category)) byCat.set(r.category, []);
      byCat.get(r.category).push(r);
    });

  for (const [cat, docs] of byCat) {
    lines.push(`### ${cat}`);
    lines.push('');
    for (const r of docs) {
      const sub = r.subcategory ? ` _(${r.subcategory})_` : '';
      lines.push(
        `- \`${r.slug}\` — **${r.title}**${sub} — ${r.chars.toLocaleString()} chars — [source](${r.url})`
      );
    }
    lines.push('');
  }

  if (failed.length) {
    lines.push('## Failed extractions');
    lines.push('');
    for (const r of failed) {
      lines.push(`- ${r.title} (${r.url}) — ${r.error}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

async function pool(items, size, worker) {
  const queue = items.slice();
  const results = [];
  const runners = Array.from({ length: size }, async () => {
    while (queue.length) {
      const item = queue.shift();
      results.push(await worker(item));
    }
  });
  await Promise.all(runners);
  return results;
}

async function main() {
  const resourcesRaw = await fs.readFile(RESOURCES, 'utf8');
  const resources = JSON.parse(resourcesRaw);
  await fs.mkdir(OUT_DIR, { recursive: true });
  await fs.mkdir(TMP_DIR, { recursive: true });

  const pdfs = resources.filter((d) => isPdfUrl(d.url));
  console.log(`Found ${pdfs.length} PDF entries (of ${resources.length} total resources).`);

  const usedSlugs = new Set();
  const tasks = pdfs.map((doc) => {
    let slug = slugify(doc.title);
    let i = 2;
    while (usedSlugs.has(slug)) slug = `${slugify(doc.title)}-${i++}`;
    usedSlugs.add(slug);
    return { doc, slug };
  });

  const rows = await pool(tasks, CONCURRENCY, async ({ doc, slug }) => {
    try {
      const { text } = await extractOne(doc, slug);
      const md = renderDocMd(doc, slug, text);
      await fs.writeFile(path.join(OUT_DIR, `${slug}.md`), md);
      console.log(`OK   ${slug.padEnd(60)} ${text.length.toString().padStart(7)} chars`);
      return { slug, ...doc, status: 'extracted', chars: text.length };
    } catch (err) {
      console.warn(`FAIL ${slug.padEnd(60)} ${err.message}`);
      return { slug, ...doc, status: 'failed', error: err.message };
    }
  });

  const indexMd = renderIndexMd(rows, pdfs.length);
  await fs.writeFile(path.join(OUT_DIR, 'INDEX.md'), indexMd);

  const ok = rows.filter((r) => r.status === 'extracted').length;
  console.log(`\nDone. ${ok}/${pdfs.length} extracted. Index at support/data/extracted/INDEX.md`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
